### ISSUE TITLE
Announce channel error

### ISSUE THREAD

**Issue by Qcat0214** [Road-block/Interruptor#1]
hey Roadblock.
I localize this addon.
But after using an interruption skill, there was a mistake:
Interruptor\core.lua:378:Unknown chat type

**Comment by Road-block** [comment]
I need a lot more details.  
What class and skill was used.  
More importantly what channel had they selected for announce?  
Only "SAY", "PARTY" and "RAID" are supported.  
I also need to see what changes you made during localization, did you edit stuff in core.lua or just loxalization.lua?

**Edit**: Nevermind, I know where's the error, fix incoming shortly.

**Comment by Road-block** [comment]
Can you attach your localization file here so I can include it with the fix?

**Comment by Qcat0214** [comment]
Used:warrior  Skill:Pummel   Set channel:raid
I only edited localization.lua file . No other files are edited.

L:RegisterTranslations("zhCN", function() return {
  ["1 = Party only, 2 = Raid only, 3 = Both"] = "1 = 只在队伍, 2 = 只在团队, 3 = 两者",
  [">>Interrupt Used!<<"] = ">>打断技已用!<<",
  ["Activate/Suspend 'Interruptor'"] = "启动/停止 'Interruptor' 插件",
  ["Active"] = "启用",
  ["Announce Text"] = "通告文本",
  ["Announce"] = "通告",
  ["Channel"] = "频道",
  ["Disabling"] = "禁用",
  ["Group Type"] = "队伍类型",
  ["Hide minimap icon"] = "隐藏小地图图标",
  ["Interrupt Announce Channel"] = "打断通报频道",
  ["Interruptor"] = "Interruptor",
  ["Party Only"] = "只在队伍",
  ["Party/Raid"] = "队伍/团队",
  ["Raid Only"] = "只在团队",
  ["Suspended"] = "暂停",
  ["Whisper a player"] = "密语玩家",
  ["Whisper"] = "密语",
  ["%s\n|cffFFA500Click:|r Cycle Group Mode|r\n|cffFFA500Right-Click:|r Options"] = "%s\n|cffFFA500点击:|r 转换队伍模式|r\n|cffFFA500右键:|r 选项",
} end)

**Comment by Road-block** [comment]
Should be fixed with  777585a  
Update from master 😺
